@baseUrl = http://localhost:5293

### List topics
GET {{baseUrl}}/api/topics

### List courses in a topic
GET {{baseUrl}}/api/topics/data-structures/courses

### List all courses (optionally filtered)
GET {{baseUrl}}/api/courses?topicId=data-structures

### Get one course
GET {{baseUrl}}/api/courses/ds-arrays-linked-lists

### Get resources for a course
GET {{baseUrl}}/api/courses/ds-arrays-linked-lists/resources
